site_url: "https://williamhorning.dev/bolt/docs"
repo_url: 'https://github.com/williamhorning/williamhorning'
edit_uri: "edit/main/bolt-docs/"
site_name: 'Bolt Docs'
site_description: 'Documentation for Bolt'
theme:
  name: terminal
  palette: dark
site_dir: '../build/output/bolt/docs'
docs_dir: './content'
